### PR TITLE
Add Waveshare RP2040 Zero board definition

### PR DESCRIPTION
**Pull request by glebsexy**
Thanks @petejohanson for thorough help with making this. 

Works with my handwired keyboard and a test one with each pin connected to a single key directly (works great for breadboard testing). Both are here: https://github.com/zyumbik/zmk-config/tree/6cc52994c382e1e5bc49de7be4680b8394d933d3

### CODE REVIEW

**Comment by tubbytwins** [comment]
Nice work indeed!  I wish I had seen this **before** I started trying to get my own RP2040-zero based keyboard working with ZMK.

Suggestions:
- Add the RGB LED, which is hard-wired to GPIO #16.
- Convince Pete to accept this pull request into the mainstream.

Have you been able to get zmk-config Github builds working with this board definition?

**Comment by glebsexy** [comment]
> Add the RGB LED, which is hard-wired to GPIO 16.

I asked Pete if that's possible. His reply was:

> We don't have a bit-bang ws2812 driver that works really, so needs to use the SPI driver to do it. Hopefully that is a pin with COPI/MOSI alternate function.

And it's not on a such pin. So until there is a custom bitbang driver in ZMK, this is not possible.

> Have you been able to get zmk-config Github builds working with this board definition?

Of course: https://github.com/glebsexy/zmk-config. This uses my updated fork and branch (see west file).

**Comment by xudongzheng** [comment]
> And it's not on a such pin. So until there is a custom bitbang driver in ZMK, this is not possible.

Upstream Zephyr has an open PR https://github.com/zephyrproject-rtos/zephyr/pull/55226 for WS2812B using PIO.

Also you might want this as a PR on the main ZMK repository.

**Comment by petejohanson** [comment]
@glebsexy Can you redo this PR and make it against `zmkfirware/zmk` instead?

**Comment by glebsexy** [comment]
done https://github.com/zmkfirmware/zmk/pull/1871

**Pull request closed without merging**
